"""Add subject table and link to files

Revision ID: 149f21b364b8
Revises: 9139cccbcbc9
Create Date: 2025-10-31 20:38:27.722084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149f21b364b8'
down_revision = '9139cccbcbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_file_subject', 'subject', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint('fk_file_subject', type_='foreignkey')
        batch_op.drop_column('subject_id')

    op.drop_table('subject')
    # ### end Alembic commands ###
